In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

In [2]:
x1 = np.random.randint(10, size = 6)
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x2 = np.random.randint(5, size=(2,2))
x2

array([[3, 2],
       [4, 0]])

In [4]:
x3 = np.random.randint(low=5, high=10, size=(2,2,3))
x3

array([[[5, 9, 7],
        [6, 5, 6]],

       [[6, 5, 6],
        [9, 8, 5]]])

In [7]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
ones.dtype

dtype('float64')

In [9]:
x3.dtype

dtype('int32')

In [10]:
x3.itemsize

4

In [11]:
x3.nbytes

48

In [24]:
twenty=np.arange(20)
twenty

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
twenty[2:10:2]

array([2, 4, 6, 8])

In [22]:
twenty[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [23]:
twenty[::-5]

array([19, 14,  9,  4])

In [25]:
# Matrix element access
mtx = np.random.randint(10, size=(3, 4))

In [27]:
mtx

array([[3, 5, 0, 2],
       [3, 8, 1, 3],
       [3, 3, 7, 0]])

In [28]:
mtx[:2, :3]

array([[3, 5, 0],
       [3, 8, 1]])

In [30]:
mtx[:1, :]

array([[3, 5, 0, 2]])

In [31]:
mtx[:, :1]

array([[3],
       [3],
       [3]])

In [35]:
mtx[2:3, 2:3]

array([[7]])

In [36]:
# any changes we make to values resulting from a variable are reflected back (references are used). A copy is created explicitly.
mtx_copy = mtx.copy()

In [37]:
mtx_copy

array([[3, 5, 0, 2],
       [3, 8, 1, 3],
       [3, 3, 7, 0]])

In [38]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [39]:
# Computation-on-arrays-broadcasting.ipynb
# https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.05-Computation-on-arrays-broadcasting.ipynb#scrollTo=TIa-eVUWdb_m

# 02.00-Linear-Algebra.ipynb
# https://colab.research.google.com/github/adhiraiyan/DeepLearningWithTF2.0/blob/master/notebooks/02.00-Linear-Algebra.ipynb